config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rciam/rciam-federation-registry:
      branch: master
      repo: https://github.com/rciam/rciam-federation-registry
    github.com/rciam/rciam-federation-registry-docs:
      branch: master
      repo: https://github.com/rciam/rciam-federation-registry-docs
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rciam/rciam-federation-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-olive-cuscus.sh
        container: qc.acc_skinny-violet-quetzal
  QC.Doc:
    repos:
      github.com/rciam/rciam-federation-registry-docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-alizarin-quetzal.sh
        container: qc.doc_chummy-wisteria-dachsbracke
      github.com/rciam/rciam-federation-registry-docs git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-violet-cassowary.sh
        container: qc.doc_scaly-magnolia-dormouse
      github.com/rciam/rciam-federation-registry-docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-vermilion-mastiff.sh
        container: qc.doc_sloppy-razzmatazz-eagle
  QC.Lic:
    repos:
      github.com/rciam/rciam-federation-registry licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-thistle-centipede.sh
        container: qc.lic_craggy-malachite-slug
  QC.Met:
    repos:
      github.com/rciam/rciam-federation-registry validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-brass-foxhound.sh
        container: qc.met_boozy-auburn-shrew
  QC.Sty:
    repos:
      github.com/rciam/rciam-federation-registry jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-pear-gecko.sh
        container: qc.sty_crappy-alizarin-ladybird
  QC.Ver:
    repos:
      github.com/rciam/rciam-federation-registry get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-alizarin-lizard.sh
        container: qc.ver_thirsty-cream-civet
timeout: 5400
